[project]
name = "music-player-v3"
version = "0.1.0"
description = "My Music Player with better GUI"
authors = [
    {name = "Zoléni Kokolo Zassi",email = "zolenikokolozassi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mutagen (>=1.47.0,<2.0.0)",
    "pygame (>=2.6.1,<3.0.0)",
    "customtkinter (>=5.2.2,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
